export type ProductCategory =
  | "camaras"
  | "lentes"
  | "mixers"
  | "monitores"
  | "audio"
  | "capturadoras"
  | "transmisores"
  | "conversores"
  | "splitters"
  | "cableado"
  | "tripodes"
  | "grips"

export type Product = {
  slug: string
  name: string
  brand: string
  category: ProductCategory
  categoryLabel: string
  pricePerDay: number // €/día, IVA incluido
  shortDescription: string
  description: string
  specs: { label: string; value: string }[]
  includes: string[]
  image: string
  gallery: string[]
  featured?: boolean
  stock: number
  /**
   * True si la imagen original viene con fondo blanco y requiere integración
   * con mix-blend-mode sobre el fondo oscuro del sitio.
   */
  whiteBg?: boolean
}

export const categories: { slug: ProductCategory; label: string; description: string }[] = [
  {
    slug: "camaras",
    label: "Cámaras",
    description: "Cámaras mirrorless y compactas listas para streaming y realización.",
  },
  {
    slug: "lentes",
    label: "Lentes",
    description: "Ópticas Sony G Master y zooms versátiles para directo.",
  },
  {
    slug: "mixers",
    label: "Mixers de vídeo",
    description: "Switchers Roland y YoloBox para realización multicámara.",
  },
  {
    slug: "monitores",
    label: "Monitores",
    description: "Monitores de campo y referencia para operador y realización.",
  },
  {
    slug: "audio",
    label: "Audio",
    description: "Mixers, interfaces, grabadores de campo e intercom.",
  },
  {
    slug: "capturadoras",
    label: "Capturadoras",
    description: "Captura USB/Thunderbolt y grabadores Atomos para streaming.",
  },
  {
    slug: "transmisores",
    label: "Transmisores inalámbricos",
    description: "Vídeo wireless HDMI/SDI Shimbol, Hollyland y Camwave.",
  },
  {
    slug: "conversores",
    label: "Conversores SDI↔HDMI",
    description: "Conversión de señal en tiempo real sin latencia.",
  },
  {
    slug: "splitters",
    label: "Splitters",
    description: "Distribución de señal de vídeo y audio.",
  },
  {
    slug: "cableado",
    label: "Cableado HDMI / SDI",
    description: "Latiguillos de cobre y fibra certificados hasta 30 m.",
  },
  {
    slug: "tripodes",
    label: "Trípodes",
    description: "Trípodes de vídeo, mini-trípodes y soportes de luz.",
  },
  {
    slug: "grips",
    label: "Grips",
    description: "Brazos mágicos, sliders y accesorios de sujeción.",
  },
]

export const products: Product[] = [
  // ───────── CÁMARAS ─────────
  {
    slug: "sony-alpha-a7iii",
    name: "Sony Alpha A7 III",
    brand: "Sony",
    category: "camaras",
    categoryLabel: "Cámaras",
    pricePerDay: 59,
    stock: 2,
    featured: true,
    shortDescription: "Mirrorless full frame 24 MP, 4K y excelente en baja luz.",
    description:
      "Cuerpo mirrorless full frame con sensor Exmor R de 24,2 MP, grabación 4K HDR y doble ranura SD. Un estándar fiable para realización multicámara y streaming musical por su rendimiento en baja luz y colorimetría Sony.",
    specs: [
      { label: "Sensor", value: "Full Frame 24,2 MP" },
      { label: "Vídeo", value: "4K 30p · FHD 120p" },
      { label: "Salida", value: "HDMI limpia (Micro HDMI)" },
      { label: "ISO", value: "100 – 51.200" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Batería NP-FZ100", "Cargador", "Correa", "Tarjeta SD 64 GB (opcional)"],
    image: "/products/sony-a7iii.webp",
    gallery: ["/products/sony-a7iii.webp", "/professional-mirrorless-cinema-camera.jpg"],
    whiteBg: true,
  },
  {
    slug: "sony-rx100-m4",
    name: "Sony RX100 M4",
    brand: "Sony",
    category: "camaras",
    categoryLabel: "Cámaras",
    pricePerDay: 30,
    stock: 2,
    shortDescription: "Compacta 1\" con 4K, ideal como cámara POV o de apoyo.",
    description:
      "Cámara compacta premium con sensor tipo 1\", obturador electrónico hasta 1/32.000s y grabación 4K. Perfecta como cámara POV, backstage o punto de vista para realización en directo.",
    specs: [
      { label: "Sensor", value: '1" Exmor RS 20,1 MP' },
      { label: "Vídeo", value: "4K 30p · Slow-mo 960 fps" },
      { label: "Lente", value: "Zeiss 24-70 f/1.8-2.8" },
      { label: "Salida", value: "Micro HDMI" },
    ],
    includes: ["Batería", "Cargador", "Funda"],
    image: "/products/sony-rx100.webp",
    gallery: ["/products/sony-rx100.webp"],
    whiteBg: true,
  },

  // ───────── LENTES ─────────
  {
    slug: "sony-gm-14mm-f28",
    name: "Sony FE 14mm f/1.8 GM",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 60,
    stock: 1,
    featured: true,
    shortDescription: "Angular G Master f/1.8, planos de escenario completos.",
    description:
      "Objetivo G Master ultra angular para directos musicales: escenarios completos, planos ambiente y bajo impacto en peso. Nitidez de referencia a plena abertura.",
    specs: [
      { label: "Focal", value: "14 mm" },
      { label: "Apertura", value: "f/1.8" },
      { label: "Montura", value: "Sony E" },
      { label: "Peso", value: "460 g" },
    ],
    includes: ["Parasol", "Tapas", "Estuche"],
    image: "/cinema-lens-black-metal-professional.jpg",
    gallery: ["/cinema-lens-black-metal-professional.jpg"],
  },
  {
    slug: "sony-50mm-f28",
    name: "Sony FE 50mm f/2.8",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Fijo 50 mm macro, foco cerrado y retratos de artista.",
    description:
      "Óptica fija 50 mm compacta con capacidad macro. Excelente para primeros planos de artista, instrumentos y detalle en realización musical.",
    specs: [
      { label: "Focal", value: "50 mm" },
      { label: "Apertura", value: "f/2.8" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Parasol", "Tapas"],
    image: "/cinema-lens-black-metal-professional.jpg",
    gallery: ["/cinema-lens-black-metal-professional.jpg"],
  },
  {
    slug: "sony-35mm",
    name: "Sony FE 35mm",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Fijo 35 mm, plano reportaje y cámara en mano.",
    description: "Focal versátil ideal para cámara en mano, ambiente de backstage y planos medios de escenario.",
    specs: [
      { label: "Focal", value: "35 mm" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Parasol", "Tapas"],
    image: "/cinema-lens-black-metal-professional.jpg",
    gallery: ["/cinema-lens-black-metal-professional.jpg"],
  },
  {
    slug: "sony-24-70mm",
    name: "Sony FE 24-70mm",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Zoom estándar todoterreno para realización.",
    description:
      "Zoom 24-70 mm, el tiro fijo por excelencia para cámaras de realización. Cubre gran angular a retrato medio sin cambio de óptica.",
    specs: [
      { label: "Focal", value: "24 – 70 mm" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Parasol", "Tapas"],
    image: "/cinema-prime-lens-set-professional.jpg",
    gallery: ["/cinema-prime-lens-set-professional.jpg"],
  },

  // ───────── MIXERS DE VÍDEO ─────────
  {
    slug: "yolobox-extreme",
    name: "YoloBox Extreme",
    brand: "YoloLiv",
    category: "mixers",
    categoryLabel: "Mixers de vídeo",
    pricePerDay: 118,
    stock: 1,
    featured: true,
    shortDescription: "Switcher 8 canales todo-en-uno con streaming RTMP.",
    description:
      "Estación de realización portátil con hasta 8 entradas (HDMI + SDI), monitor táctil, streaming directo a RTMP/NDI, grabación interna y transición PGM/PVW. La solución más completa para streaming de conciertos sin rack.",
    specs: [
      { label: "Entradas", value: "4x HDMI + 4x SDI" },
      { label: "Salidas", value: "HDMI + SDI + USB" },
      { label: "Streaming", value: "RTMP · NDI · YouTube · Twitch" },
      { label: "Resolución", value: "Hasta 4K 60p" },
      { label: "Pantalla", value: 'Táctil 10.1"' },
    ],
    includes: ["Fuente de alimentación", "Funda de transporte"],
    image: "/yolobox-extreme-portable-switcher.jpg",
    gallery: ["/yolobox-extreme-portable-switcher.jpg", "/video-switcher-mixer-broadcast-buttons.jpg"],
  },
  {
    slug: "roland-v1-hd",
    name: "Roland V-1HD",
    brand: "Roland",
    category: "mixers",
    categoryLabel: "Mixers de vídeo",
    pricePerDay: 28,
    stock: 1,
    featured: true,
    shortDescription: "Switcher HDMI 4 canales compacto y fiable.",
    description:
      "Mezclador HDMI de 4 canales con T-bar, efectos y conmutación limpia. La opción compacta para directos pequeños y streaming musical cuando no se necesita SDI.",
    specs: [
      { label: "Entradas", value: "4x HDMI" },
      { label: "Salidas", value: "2x HDMI + USB" },
      { label: "Resolución", value: "1080p" },
      { label: "Transiciones", value: "Cut / Mix / Wipe" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/roland-v1hd-compact-video-switcher.jpg",
    gallery: ["/roland-v1hd-compact-video-switcher.jpg", "/roland-video-mixer-professional.jpg"],
  },
  {
    slug: "switcher-hdmi-generico",
    name: "Switcher HDMI genérico",
    brand: "Generic",
    category: "mixers",
    categoryLabel: "Mixers de vídeo",
    pricePerDay: 1,
    stock: 1,
    shortDescription: "Switcher HDMI básico para backup o monitorado.",
    description: "Switcher HDMI de 4 entradas para tareas sencillas de conmutación, redundancia o monitorado.",
    specs: [
      { label: "Entradas", value: "4x HDMI" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/video-switcher-mixer-broadcast-buttons.jpg",
    gallery: ["/video-switcher-mixer-broadcast-buttons.jpg"],
  },

  // ───────── MONITORES ─────────
  {
    slug: "monitor-de-campo",
    name: "Monitor de campo 7\"",
    brand: "Generic",
    category: "monitores",
    categoryLabel: "Monitores",
    pricePerDay: 13,
    stock: 1,
    shortDescription: 'Monitor on-camera 7" HDMI para operador.',
    description:
      'Monitor de campo HDMI de 7" con peaking, falso color y zebra. Para operador, foquista o referencia de realización.',
    specs: [
      { label: "Tamaño", value: "7 pulgadas" },
      { label: "Entradas", value: "HDMI" },
      { label: "Brillo", value: "400 nits" },
    ],
    includes: ["Batería NP-F", "Cargador", "Cable HDMI 50 cm"],
    image: "/professional-field-monitor-display.jpg",
    gallery: ["/professional-field-monitor-display.jpg"],
  },
  {
    slug: "monitor-neofyte",
    name: "Monitor Neofyte",
    brand: "Neofyte",
    category: "monitores",
    categoryLabel: "Monitores",
    pricePerDay: 15,
    stock: 1,
    shortDescription: "Monitor de referencia para realización.",
    description: "Monitor compacto pensado como referencia PGM/PVW en puesto de realización.",
    specs: [
      { label: "Entradas", value: "HDMI" },
      { label: "Alimentación", value: "DC 12V" },
    ],
    includes: ["Fuente de alimentación", "Soporte"],
    image: "/professional-field-monitor-display.jpg",
    gallery: ["/professional-field-monitor-display.jpg"],
  },

  // ───────── AUDIO ─────────
  {
    slug: "zoom-livetrak-l8",
    name: "Zoom LiveTrak L-8",
    brand: "Zoom",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 42,
    stock: 1,
    shortDescription: "Mixer/grabadora 8 canales con pads y faders.",
    description:
      "Mesa de mezclas y grabadora multipista de 8 canales con 6 pads asignables y monitorado independiente. Ideal para podcast, directo y realización musical pequeña.",
    specs: [
      { label: "Canales", value: "8 (6 XLR/TRS + 2 stereo)" },
      { label: "Grabación", value: "12 pistas simultáneas" },
      { label: "Interfaz", value: "USB audio 12-in / 4-out" },
    ],
    includes: ["Fuente de alimentación", "Cable USB"],
    image: "/zoom-l8-podcast-mixer.jpg",
    gallery: ["/zoom-l8-podcast-mixer.jpg"],
  },
  {
    slug: "focusrite-scarlett-2i4",
    name: "Focusrite Scarlett 2i4",
    brand: "Focusrite",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 22,
    stock: 1,
    shortDescription: "Interfaz de audio USB 2 in / 4 out.",
    description:
      "Interfaz de audio USB con dos preamplificadores Focusrite, ideal para captura de audio broadcast en streaming.",
    specs: [
      { label: "Entradas", value: "2x XLR/TRS combo" },
      { label: "Salidas", value: "4 (2 monitor + 2 line)" },
      { label: "Conversión", value: "24 bit / 192 kHz" },
    ],
    includes: ["Cable USB"],
    image: "/products/focusrite-scarlett.avif",
    gallery: ["/products/focusrite-scarlett.avif"],
    whiteBg: true,
  },
  {
    slug: "tascam-dr40",
    name: "Tascam DR-40",
    brand: "Tascam",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 15,
    stock: 1,
    shortDescription: "Grabadora de campo 4 pistas con XLR.",
    description: "Grabadora de mano de 4 pistas con micros estéreo y entradas XLR/TRS. Respaldo de audio o backup.",
    specs: [
      { label: "Pistas", value: "4" },
      { label: "Entradas", value: "2x XLR/TRS + micros internos" },
      { label: "Soporte", value: "SD / SDHC / SDXC" },
    ],
    includes: ["Pilas AA", "Funda"],
    image: "/tascam-dr40-audio-recorder.jpg",
    gallery: ["/tascam-dr40-audio-recorder.jpg"],
  },
  {
    slug: "hollyland-intercom-solidcom",
    name: "Hollyland Solidcom Intercom",
    brand: "Hollyland",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 48,
    stock: 1,
    featured: true,
    shortDescription: "Sistema intercom wireless, 3 headsets.",
    description:
      "Sistema de intercom inalámbrico full-duplex con 3 estaciones/headsets. Comunicación entre realización, cámaras y FOH sin cableado.",
    specs: [
      { label: "Unidades", value: "3 headsets + hub" },
      { label: "Alcance", value: "Hasta 350 m línea de vista" },
      { label: "Autonomía", value: "10 h" },
    ],
    includes: ["3x headsets", "Base/hub", "Cables de carga"],
    image: "/products/intercom-hollyland.webp",
    gallery: ["/products/intercom-hollyland.webp"],
    whiteBg: true,
  },
  {
    slug: "hollyland-lark-wireless-mics",
    name: "Hollyland Lark · micros inalámbricos",
    brand: "Hollyland",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 16,
    stock: 1,
    shortDescription: "Kit de microfonía inalámbrica de solapa.",
    description: "Sistema dual de micrófonos inalámbricos de solapa con caja de carga y receptor de cámara.",
    specs: [
      { label: "Canales", value: "2" },
      { label: "Alcance", value: "200 m" },
      { label: "Autonomía", value: "8 h" },
    ],
    includes: ["2x TX", "1x RX", "Caja de carga", "Cables TRS/TRRS/Lightning"],
    image: "/hollyland-lark-wireless-microphone-system.jpg",
    gallery: ["/hollyland-lark-wireless-microphone-system.jpg"],
  },

  // ───────── CAPTURADORAS ─────────
  {
    slug: "atomos-ninja-4k",
    name: "Atomos Ninja 4K",
    brand: "Atomos",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 30,
    stock: 1,
    featured: true,
    shortDescription: "Grabador/monitor 4K ProRes con HDMI.",
    description:
      "Grabador y monitor 4K con grabación ProRes/DNx vía HDMI. Monitor brillante para operador y respaldo de señal sin compresión.",
    specs: [
      { label: "Entradas", value: "HDMI 2.0" },
      { label: "Códecs", value: "ProRes · DNxHR" },
      { label: "Pantalla", value: '5" 1000 nits' },
    ],
    includes: ["2x batería NP-F", "Cargador", "SSD 500 GB"],
    image: "/atomos-ninja-field-monitor-recorder.jpg",
    gallery: ["/atomos-ninja-field-monitor-recorder.jpg"],
  },
  {
    slug: "atomos-ninja-2",
    name: "Atomos Ninja 2",
    brand: "Atomos",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 25,
    stock: 1,
    shortDescription: "Grabador externo Full HD ProRes.",
    description: "Grabador externo Full HD ProRes por HDMI. Opción económica para grabación de backup.",
    specs: [
      { label: "Entradas", value: "HDMI" },
      { label: "Códecs", value: "ProRes" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["Batería", "Cargador", "HDD"],
    image: "/atomos-ninja-field-monitor-recorder.jpg",
    gallery: ["/atomos-ninja-field-monitor-recorder.jpg"],
  },
  {
    slug: "avio-4k-capture",
    name: "AVIO 4K Capture Card",
    brand: "AVIO",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 30,
    stock: 1,
    shortDescription: "Tarjeta de captura 4K HDMI → USB-C.",
    description:
      "Capturadora externa 4K con loop-out HDMI. Pensada para alimentar un PC de streaming desde cualquier cámara con salida HDMI.",
    specs: [
      { label: "Entrada", value: "HDMI 2.0" },
      { label: "Salida", value: "USB-C 3.0" },
      { label: "Resolución", value: "4K 30p · 1080p 60p" },
    ],
    includes: ["Cable USB-C"],
    image: "/products/avio-4k.webp",
    gallery: ["/products/avio-4k.webp"],
    whiteBg: true,
  },
  {
    slug: "capturadora-usb-hd",
    name: "Capturadora USB HD",
    brand: "Generic",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 1,
    stock: 3,
    shortDescription: "Capturadora USB HDMI 1080p.",
    description:
      "Capturadora USB HDMI genérica, 1080p. Útil para streaming básico o como backup en realización.",
    specs: [
      { label: "Entrada", value: "HDMI" },
      { label: "Salida", value: "USB 2.0" },
      { label: "Resolución", value: "1080p 30" },
    ],
    includes: ["Cable USB"],
    image: "/products/capturadora-generica.jpg",
    gallery: ["/products/capturadora-generica.jpg"],
    whiteBg: true,
  },

  // ───────── TRANSMISORES INALÁMBRICOS ─────────
  {
    slug: "hollyland-4k-wireless",
    name: "Hollyland 4K Wireless",
    brand: "Hollyland",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 30,
    stock: 1,
    featured: true,
    shortDescription: "Transmisor inalámbrico 4K hasta 150 m.",
    description:
      "Transmisor wireless 4K con HDMI para realización sin cables. Baja latencia y alcance útil en recintos grandes.",
    specs: [
      { label: "Entrada/Salida", value: "HDMI 2.0" },
      { label: "Alcance", value: "150 m" },
      { label: "Latencia", value: "< 60 ms" },
      { label: "Resolución", value: "4K 30p / 1080p 60p" },
    ],
    includes: ["TX + RX", "Antenas", "Cables HDMI cortos", "Baterías NP-F"],
    image: "/teradek-wireless-video-transmitter.jpg",
    gallery: ["/teradek-wireless-video-transmitter.jpg"],
  },
  {
    slug: "shimbol-tp-mini",
    name: "Shimbol TP Mini Sistema",
    brand: "Shimbol",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 23,
    stock: 3,
    shortDescription: "Transmisor wireless HDMI compacto, 100 m.",
    description:
      "Sistema inalámbrico HDMI compacto Shimbol TP Mini. Pareja TX/RX para envío a realización, monitor de director o streaming.",
    specs: [
      { label: "Entrada/Salida", value: "HDMI" },
      { label: "Alcance", value: "100 m línea de vista" },
      { label: "Resolución", value: "1080p 60" },
    ],
    includes: ["TX + RX", "Cables HDMI", "Baterías"],
    image: "/hollyland-wireless-video-transmitter-compact.jpg",
    gallery: ["/hollyland-wireless-video-transmitter-compact.jpg"],
  },
  {
    slug: "transmisor-generico-hdmi",
    name: "Transmisor HDMI genérico",
    brand: "Generic",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 7,
    stock: 1,
    shortDescription: "Transmisor HDMI inalámbrico de apoyo.",
    description: "Pareja TX/RX HDMI para distancias cortas. Útil como backup o redundancia.",
    specs: [
      { label: "Entrada/Salida", value: "HDMI" },
      { label: "Alcance", value: "50 m" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["TX + RX", "Cables"],
    image: "/hollyland-wireless-video-transmitter-compact.jpg",
    gallery: ["/hollyland-wireless-video-transmitter-compact.jpg"],
  },
  {
    slug: "camwave-transmitter",
    name: "Camwave Transmisor",
    brand: "Camwave",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 5,
    stock: 1,
    shortDescription: "Transmisor wireless Full HD low-cost.",
    description: "Transmisor inalámbrico compacto para distancias cortas, ideal como pool de cámara a monitor.",
    specs: [
      { label: "Entrada", value: "HDMI" },
      { label: "Alcance", value: "30 m" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["TX + RX"],
    image: "/hollyland-wireless-video-transmitter-compact.jpg",
    gallery: ["/hollyland-wireless-video-transmitter-compact.jpg"],
  },

  // ───────── CONVERSORES ─────────
  {
    slug: "conversor-hdmi-a-sdi",
    name: "Conversor HDMI → SDI",
    brand: "Generic",
    category: "conversores",
    categoryLabel: "Conversores",
    pricePerDay: 11,
    stock: 2,
    shortDescription: "Convierte HDMI a 3G-SDI con loop.",
    description:
      "Conversor de HDMI a SDI compacto, con salida loop. Imprescindible para integrar cámaras HDMI en flujos SDI de realización.",
    specs: [
      { label: "Entrada", value: "HDMI" },
      { label: "Salida", value: "2x 3G-SDI" },
      { label: "Resolución", value: "Hasta 1080p 60" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/products/conversor-hdmi-sdi.jpg",
    gallery: ["/products/conversor-hdmi-sdi.jpg"],
    whiteBg: true,
  },
  {
    slug: "conversor-sdi-a-hdmi",
    name: "Conversor SDI → HDMI",
    brand: "Generic",
    category: "conversores",
    categoryLabel: "Conversores",
    pricePerDay: 11,
    stock: 1,
    shortDescription: "Convierte 3G-SDI a HDMI.",
    description:
      "Conversor SDI a HDMI, necesario para sacar señal SDI a monitores de consumo, capturadoras o proyectores.",
    specs: [
      { label: "Entrada", value: "3G-SDI" },
      { label: "Salida", value: "HDMI" },
      { label: "Resolución", value: "Hasta 1080p 60" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/products/conversor-sdi-hdmi.avif",
    gallery: ["/products/conversor-sdi-hdmi.avif"],
    whiteBg: true,
  },

  // ───────── SPLITTERS ─────────
  {
    slug: "splitter-video-hdmi",
    name: "Splitter de vídeo HDMI",
    brand: "Generic",
    category: "splitters",
    categoryLabel: "Splitters",
    pricePerDay: 2,
    stock: 2,
    shortDescription: "Distribuidor HDMI 1×4.",
    description: "Splitter HDMI 1×4 para distribuir una misma señal a varios destinos (monitorado, streaming, proyección).",
    specs: [
      { label: "Entradas", value: "1x HDMI" },
      { label: "Salidas", value: "4x HDMI" },
      { label: "Resolución", value: "1080p 60" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/hdmi-splitter-8-port-professional-rack.jpg",
    gallery: ["/hdmi-splitter-8-port-professional-rack.jpg"],
  },
  {
    slug: "splitter-audio",
    name: "Splitter de audio",
    brand: "Generic",
    category: "splitters",
    categoryLabel: "Splitters",
    pricePerDay: 2,
    stock: 1,
    shortDescription: "Distribuidor de audio analógico.",
    description: "Splitter de audio para enviar una misma señal a varios destinos sin pérdida.",
    specs: [
      { label: "Entradas", value: "1 estéreo" },
      { label: "Salidas", value: "4 estéreo" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/sdi-splitter-distributor-rack-professional.jpg",
    gallery: ["/sdi-splitter-distributor-rack-professional.jpg"],
  },

  // ───────── CABLEADO ─────────
  {
    slug: "cable-hdmi-fibra-30m",
    name: "Cable HDMI fibra óptica 30 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 14,
    stock: 8,
    shortDescription: "HDMI 2.0 fibra óptica 4K, 30 metros.",
    description:
      "Cable HDMI de fibra óptica activa de 30 m. Imprescindible para tiradas largas entre escenario y realización sin pérdida de señal 4K.",
    specs: [
      { label: "Longitud", value: "30 m" },
      { label: "Tipo", value: "Fibra óptica activa" },
      { label: "Resolución", value: "4K 60p" },
    ],
    includes: ["Cable"],
    image: "/products/cable-hdmi-fibra-30m.jpg",
    gallery: ["/products/cable-hdmi-fibra-30m.jpg"],
    whiteBg: true,
  },
  {
    slug: "cable-sdi-30m",
    name: "Cable SDI 30 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 22,
    stock: 1,
    shortDescription: "Cable 3G-SDI con conectores BNC, 30 m.",
    description:
      "Cable 3G-SDI de 30 m con BNC. Estándar para distribución de vídeo en realización broadcast y en directo.",
    specs: [
      { label: "Longitud", value: "30 m" },
      { label: "Conectores", value: "BNC · BNC" },
      { label: "Ancho de banda", value: "3G-SDI" },
    ],
    includes: ["Cable"],
    image: "/products/cable-sdi-30m.jpg",
    gallery: ["/products/cable-sdi-30m.jpg"],
    whiteBg: true,
  },
  {
    slug: "cable-hdmi-10m",
    name: "Cable HDMI 10 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 2,
    shortDescription: "HDMI 2.0 de cobre, 10 m.",
    description: "Latiguillo HDMI de cobre de 10 metros, apto para 1080p.",
    specs: [
      { label: "Longitud", value: "10 m" },
      { label: "Tipo", value: "Cobre" },
    ],
    includes: ["Cable"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "cable-hdmi-5m",
    name: "Cable HDMI 5 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 4,
    shortDescription: "HDMI 2.0 de cobre, 5 m.",
    description: "Latiguillo HDMI de cobre, distancia corta para interconexión en rack.",
    specs: [
      { label: "Longitud", value: "5 m" },
      { label: "Tipo", value: "Cobre" },
    ],
    includes: ["Cable"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "cable-mini-hdmi-a-hdmi",
    name: "Cable mini HDMI → HDMI",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Cable mini HDMI para cámaras.",
    description: "Cable mini HDMI a HDMI estándar, para salida de cámaras tipo Sony RX100 o DSLR.",
    specs: [
      { label: "Longitud", value: "1 m" },
      { label: "Tipo", value: "Mini HDMI · HDMI" },
    ],
    includes: ["Cable"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "cable-hdmi-corto-50cm",
    name: "Cable HDMI corto 25-50 cm",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Latiguillos cortos para jaula y rig.",
    description: "Cables HDMI cortos de 25 y 50 cm, ideales para monitor on-camera o interconexión en rig.",
    specs: [
      { label: "Longitud", value: "25 – 50 cm" },
      { label: "Color", value: "Amarillo alta visibilidad" },
    ],
    includes: ["Cable"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "adaptador-mini-hdmi",
    name: "Adaptador mini HDMI",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Adaptador mini HDMI a HDMI hembra.",
    description: "Adaptador compacto para convertir salida mini HDMI en HDMI estándar.",
    specs: [
      { label: "Tipo", value: "Mini HDMI M · HDMI H" },
    ],
    includes: ["Adaptador"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "cable-rca-5m",
    name: "Cable RCA 5 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Cable RCA estéreo, 5 m.",
    description: "Cable RCA estéreo de 5 m para envíos de audio.",
    specs: [
      { label: "Longitud", value: "5 m" },
      { label: "Conectores", value: "2x RCA · 2x RCA" },
    ],
    includes: ["Cable"],
    image: "/coiled-bnc-sdi-cable-professional.jpg",
    gallery: ["/coiled-bnc-sdi-cable-professional.jpg"],
  },

  // ───────── TRÍPODES ─────────
  {
    slug: "tripode-heavy-duty",
    name: "Trípode Heavy Duty",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Trípode de vídeo robusto con cabeza fluida.",
    description:
      "Trípode heavy duty con cabeza fluida, apto para cámaras de realización con óptica cinema.",
    specs: [
      { label: "Carga máxima", value: "10 kg" },
      { label: "Altura máxima", value: "170 cm" },
      { label: "Cabeza", value: "Fluida con contrabalance" },
    ],
    includes: ["Zapata", "Barra de pan", "Funda"],
    image: "/professional-video-tripod-fluid-head.jpg",
    gallery: ["/professional-video-tripod-fluid-head.jpg"],
  },
  {
    slug: "tripode-gaver",
    name: "Trípode Gaver",
    brand: "Gaver",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 16,
    stock: 1,
    shortDescription: "Trípode profesional ligero.",
    description: "Trípode de vídeo ligero Gaver con cabeza fluida. Buen equilibrio entre peso y capacidad.",
    specs: [
      { label: "Carga máxima", value: "6 kg" },
      { label: "Altura máxima", value: "160 cm" },
    ],
    includes: ["Zapata", "Funda"],
    image: "/professional-video-tripod-fluid-head.jpg",
    gallery: ["/professional-video-tripod-fluid-head.jpg"],
  },
  {
    slug: "monopie-gaver",
    name: "Monopie Gaver",
    brand: "Gaver",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 16,
    stock: 1,
    shortDescription: "Monopie de vídeo con base estable.",
    description: "Monopie con base desplegable para operador en directo.",
    specs: [
      { label: "Carga máxima", value: "5 kg" },
      { label: "Altura máxima", value: "180 cm" },
    ],
    includes: ["Base plegable", "Funda"],
    image: "/professional-video-tripod-fluid-head.jpg",
    gallery: ["/professional-video-tripod-fluid-head.jpg"],
  },
  {
    slug: "tripode-pequeno-estable",
    name: "Trípode pequeño estable",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 7,
    stock: 1,
    shortDescription: "Trípode compacto de bajo perfil.",
    description: "Trípode compacto y estable Manbily, cabeza plegable. Para cámaras pequeñas o en ubicaciones de bajo perfil.",
    specs: [
      { label: "Altura máxima", value: "20 cm (plegable)" },
      { label: "Marca", value: "Manbily" },
    ],
    includes: ["Trípode plegable"],
    image: "/products/tripode-base-fuerte.jpg",
    gallery: ["/products/tripode-base-fuerte.jpg"],
    whiteBg: true,
  },
  {
    slug: "tripode-mini",
    name: "Trípode mini",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 5,
    shortDescription: "Mini-trípode para cámara compacta y POV.",
    description: "Trípode de mesa para RX100, móviles o cámaras de acción.",
    specs: [
      { label: "Altura máxima", value: "20 cm" },
    ],
    includes: ["Trípode"],
    image: "/professional-video-tripod-fluid-head.jpg",
    gallery: ["/professional-video-tripod-fluid-head.jpg"],
  },
  {
    slug: "tripode-manfrotto-mini",
    name: "Trípode Manfrotto mini",
    brand: "Manfrotto",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 4,
    shortDescription: "Mini trípode Manfrotto para POV.",
    description: "Trípode Manfrotto de mesa, calidad superior a los genéricos, tope de carga mayor.",
    specs: [
      { label: "Altura máxima", value: "25 cm" },
    ],
    includes: ["Trípode"],
    image: "/professional-video-tripod-fluid-head.jpg",
    gallery: ["/professional-video-tripod-fluid-head.jpg"],
  },
  {
    slug: "tripode-base-larga",
    name: "Trípode base larga",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Mini-trípode con base larga.",
    description: "Trípode con base alargada, útil para colocar cámaras sobre superficies irregulares.",
    specs: [
      { label: "Altura máxima", value: "15 cm" },
    ],
    includes: ["Trípode"],
    image: "/professional-video-tripod-fluid-head.jpg",
    gallery: ["/professional-video-tripod-fluid-head.jpg"],
  },
  {
    slug: "tripode-fondo-blanco",
    name: "Trípode para fondo",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 1,
    shortDescription: "Soporte telescópico para fondos.",
    description: "Sistema de soporte de fondo para plató (dos pies + barra horizontal).",
    specs: [
      { label: "Altura máxima", value: "300 cm" },
      { label: "Ancho", value: "3 m" },
    ],
    includes: ["2 pies", "Barra telescópica", "Funda"],
    image: "/light-stand-tripod-telescopic.jpg",
    gallery: ["/light-stand-tripod-telescopic.jpg"],
  },
  {
    slug: "tripode-de-luz",
    name: "Trípode de luz",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 7,
    shortDescription: "Pie de luz telescópico.",
    description: "Pie de luz estándar para LED on-stand, flashes o accesorios con rosca 1/4\" y 3/8\".",
    specs: [
      { label: "Altura máxima", value: "220 cm" },
      { label: "Rosca", value: '1/4" y 3/8"' },
    ],
    includes: ["Pie de luz"],
    image: "/light-stand-tripod-telescopic.jpg",
    gallery: ["/light-stand-tripod-telescopic.jpg"],
  },

  // ───────── GRIPS ─────────
  {
    slug: "brazo-manfrotto-grande",
    name: "Brazo Manfrotto grande",
    brand: "Manfrotto",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 12,
    stock: 3,
    shortDescription: "Brazo mágico Manfrotto articulado.",
    description:
      "Brazo articulado Manfrotto grande, muy resistente. Para sujetar monitores, luces o cámaras pequeñas a estructuras.",
    specs: [
      { label: "Carga", value: "Hasta 3 kg" },
      { label: "Extensión", value: "55 cm" },
    ],
    includes: ["Brazo", "Super Clamp"],
    image: "/products/brazo-manfrotto-grande.jpg",
    gallery: ["/products/brazo-manfrotto-grande.jpg"],
    whiteBg: true,
  },
  {
    slug: "brazo-magico-neewer-std",
    name: "Brazo mágico Neewer · estándar",
    brand: "Neewer",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Brazo articulado para monitor on-camera.",
    description: "Brazo mágico Neewer tamaño estándar para monitor, luz o micro en jaula.",
    specs: [
      { label: "Carga", value: "Hasta 1.5 kg" },
      { label: "Longitud", value: "28 cm" },
    ],
    includes: ["Brazo", "Super Clamp"],
    image: "/products/brazo-magico-standard.jpg",
    gallery: ["/products/brazo-magico-standard.jpg"],
    whiteBg: true,
  },
  {
    slug: "brazo-magico-neewer-med",
    name: "Brazo mágico Neewer · mediano",
    brand: "Neewer",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 2,
    stock: 6,
    shortDescription: "Brazo articulado mediano.",
    description: "Brazo mágico Neewer mediano con super clamp, para accesorios ligeros en jaula o estructura.",
    specs: [
      { label: "Longitud", value: "20 cm" },
    ],
    includes: ["Brazo", "Super Clamp"],
    image: "/products/brazo-magico-mediano.jpg",
    gallery: ["/products/brazo-magico-mediano.jpg"],
    whiteBg: true,
  },
  {
    slug: "brazo-magico-neewer-peq",
    name: "Brazo mágico Neewer · pequeño",
    brand: "Neewer",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Brazo articulado pequeño.",
    description: "Brazo mágico pequeño, ideal para micros, luces de acción o accesorios en jaula.",
    specs: [
      { label: "Longitud", value: "12 cm" },
    ],
    includes: ["Brazo"],
    image: "/neewer-magic-arm-articulated-grip.jpg",
    gallery: ["/neewer-magic-arm-articulated-grip.jpg"],
  },
  {
    slug: "slider-motorizado",
    name: "Slider motorizado",
    brand: "Generic",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 1,
    shortDescription: "Slider motorizado compacto.",
    description: "Slider motorizado para movimientos de cámara cortos con control de velocidad.",
    specs: [
      { label: "Recorrido", value: "40 cm" },
      { label: "Motorización", value: "Velocidad variable" },
    ],
    includes: ["Slider", "Mando", "Batería"],
    image: "/motorized-camera-slider-rail.jpg",
    gallery: ["/motorized-camera-slider-rail.jpg"],
  },
  {
    slug: "palo-selfie",
    name: "Palo selfie extensible",
    brand: "Generic",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 4,
    shortDescription: "Palo extensible para cámara compacta.",
    description: "Palo extensible para RX100, móviles y cámaras de acción. Útil para planos POV y backstage.",
    specs: [
      { label: "Longitud", value: "25 – 90 cm" },
    ],
    includes: ["Palo"],
    image: "/neewer-magic-arm-articulated-grip.jpg",
    gallery: ["/neewer-magic-arm-articulated-grip.jpg"],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getCategory(slug: ProductCategory) {
  return categories.find((c) => c.slug === slug)
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.category === category)
}
