export type ProductCategory =
  | "camaras"
  | "lentes"
  | "mixers"
  | "monitores"
  | "audio"
  | "capturadoras"
  | "transmisores"
  | "conversores"
  | "splitters"
  | "cableado"
  | "tripodes"
  | "grips"
  | "luces"
  | "baterias"

export type Product = {
  slug: string
  name: string
  brand: string
  category: ProductCategory
  categoryLabel: string
  pricePerDay: number // €/día, IVA incluido
  shortDescription: string
  description: string
  specs: { label: string; value: string }[]
  includes: string[]
  image: string
  gallery: string[]
  featured?: boolean
  stock: number
  /**
   * True si la imagen original viene con fondo blanco y requiere integración
   * con mix-blend-mode sobre un placa clara para fundirla con el fondo oscuro.
   */
  whiteBg?: boolean
}

export const categories: { slug: ProductCategory; label: string; description: string }[] = [
  {
    slug: "camaras",
    label: "Cámaras",
    description: "Cámaras mirrorless y compactas listas para streaming y realización.",
  },
  {
    slug: "lentes",
    label: "Lentes",
    description: "Ópticas Sony G Master y zooms versátiles para directo.",
  },
  {
    slug: "mixers",
    label: "Mixers de vídeo",
    description: "Switchers Roland y YoloBox para realización multicámara.",
  },
  {
    slug: "monitores",
    label: "Monitores",
    description: "Monitores de campo y referencia para operador y realización.",
  },
  {
    slug: "audio",
    label: "Audio",
    description: "Mixers, interfaces, grabadores de campo e intercom.",
  },
  {
    slug: "capturadoras",
    label: "Capturadoras",
    description: "Captura USB/Thunderbolt y grabadores Atomos para streaming.",
  },
  {
    slug: "transmisores",
    label: "Transmisores inalámbricos",
    description: "Vídeo wireless HDMI/SDI Shimbol, Hollyland y Camwave.",
  },
  {
    slug: "conversores",
    label: "Conversores SDI↔HDMI",
    description: "Conversión de señal en tiempo real sin latencia.",
  },
  {
    slug: "splitters",
    label: "Splitters",
    description: "Distribución de señal de vídeo y audio.",
  },
  {
    slug: "cableado",
    label: "Cableado HDMI / SDI",
    description: "Latiguillos de cobre y fibra certificados hasta 30 m.",
  },
  {
    slug: "tripodes",
    label: "Trípodes",
    description: "Trípodes de vídeo, mini-trípodes y soportes de luz.",
  },
  {
    slug: "grips",
    label: "Grips",
    description: "Brazos mágicos, sliders y accesorios de sujeción.",
  },
  {
    slug: "luces",
    label: "Luces",
    description: "Tubos LED Godox, paneles Neewer y RGB portátiles.",
  },
  {
    slug: "baterias",
    label: "Baterías",
    description: "Baterías NP-F, power banks y cargadores dobles.",
  },
]

export const products: Product[] = [
  // ───────── CÁMARAS ─────────
  {
    slug: "sony-alpha-a7iii",
    name: "Sony Alpha A7 III",
    brand: "Sony",
    category: "camaras",
    categoryLabel: "Cámaras",
    pricePerDay: 59,
    stock: 2,
    featured: true,
    shortDescription: "Mirrorless full frame 24 MP, 4K y excelente en baja luz.",
    description:
      "Cuerpo mirrorless full frame con sensor Exmor R de 24,2 MP, grabación 4K HDR y doble ranura SD. Un estándar fiable para realización multicámara y streaming musical por su rendimiento en baja luz y colorimetría Sony.",
    specs: [
      { label: "Sensor", value: "Full Frame 24,2 MP" },
      { label: "Vídeo", value: "4K 30p · FHD 120p" },
      { label: "Salida", value: "HDMI limpia (Micro HDMI)" },
      { label: "ISO", value: "100 – 51.200" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Batería NP-FZ100", "Cargador", "Correa", "Tarjeta SD 64 GB (opcional)"],
    image: "/products/sony-a7iii-body.jpg",
    gallery: ["/products/sony-a7iii-body.jpg"],
  },
  {
    slug: "sony-rx100-m4",
    name: "Sony RX100 M4",
    brand: "Sony",
    category: "camaras",
    categoryLabel: "Cámaras",
    pricePerDay: 30,
    stock: 2,
    shortDescription: 'Compacta 1" con 4K, ideal como cámara POV o de apoyo.',
    description:
      'Cámara compacta premium con sensor tipo 1", obturador electrónico hasta 1/32.000s y grabación 4K. Perfecta como cámara POV, backstage o punto de vista para realización en directo.',
    specs: [
      { label: "Sensor", value: '1" Exmor RS 20,1 MP' },
      { label: "Vídeo", value: "4K 30p · Slow-mo 960 fps" },
      { label: "Lente", value: "Zeiss 24-70 f/1.8-2.8" },
      { label: "Salida", value: "Micro HDMI" },
    ],
    includes: ["Batería", "Cargador", "Funda"],
    image: "/products/sony-rx100-dark.jpg",
    gallery: ["/products/sony-rx100-dark.jpg"],
  },

  // ───────── LENTES ─────────
  {
    slug: "sony-gm-14mm-f28",
    name: "Sony FE 14mm f/1.8 GM",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 60,
    stock: 1,
    featured: true,
    shortDescription: "Angular G Master f/1.8, planos de escenario completos.",
    description:
      "Objetivo G Master ultra angular para directos musicales: escenarios completos, planos ambiente y bajo impacto en peso. Nitidez de referencia a plena abertura.",
    specs: [
      { label: "Focal", value: "14 mm" },
      { label: "Apertura", value: "f/1.8" },
      { label: "Montura", value: "Sony E" },
      { label: "Peso", value: "460 g" },
    ],
    includes: ["Parasol", "Tapas", "Estuche"],
    image: "/products/sony-lente-14gm.jpg",
    gallery: ["/products/sony-lente-14gm.jpg"],
  },
  {
    slug: "sony-50mm-f18",
    name: "Sony FE 50mm f/1.8",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Fijo 50 mm, retratos de artista con bokeh cremoso.",
    description:
      "Óptica fija 50 mm compacta y luminosa. Excelente para primeros planos de artista, instrumentos y detalle en realización musical.",
    specs: [
      { label: "Focal", value: "50 mm" },
      { label: "Apertura", value: "f/1.8" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Parasol", "Tapas"],
    image: "/products/sony-lente-50.jpg",
    gallery: ["/products/sony-lente-50.jpg"],
  },
  {
    slug: "sony-35mm-f18",
    name: "Sony FE 35mm f/1.8",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Fijo 35 mm, plano reportaje y cámara en mano.",
    description:
      "Focal versátil ideal para cámara en mano, ambiente de backstage y planos medios de escenario. OSS estabilizador.",
    specs: [
      { label: "Focal", value: "35 mm" },
      { label: "Apertura", value: "f/1.8" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Parasol", "Tapas"],
    image: "/products/sony-lente-35.jpg",
    gallery: ["/products/sony-lente-35.jpg"],
  },
  {
    slug: "sony-28-70mm",
    name: "Sony FE 28-70mm f/3.5-5.6 OSS",
    brand: "Sony",
    category: "lentes",
    categoryLabel: "Lentes",
    pricePerDay: 20,
    stock: 1,
    shortDescription: "Zoom estándar todoterreno para realización.",
    description:
      "Zoom 28-70 mm con estabilizador óptico, el tiro fijo por excelencia para cámaras de realización. Cubre gran angular a retrato medio sin cambio de óptica.",
    specs: [
      { label: "Focal", value: "28 – 70 mm" },
      { label: "Apertura", value: "f/3.5 – 5.6" },
      { label: "Estabilizador", value: "OSS" },
      { label: "Montura", value: "Sony E" },
    ],
    includes: ["Parasol", "Tapas"],
    image: "/products/sony-lente-28-70.jpg",
    gallery: ["/products/sony-lente-28-70.jpg"],
  },

  // ───────── MIXERS DE VÍDEO ─────────
  {
    slug: "yolobox-extreme",
    name: "YoloBox Extreme",
    brand: "YoloLiv",
    category: "mixers",
    categoryLabel: "Mixers de vídeo",
    pricePerDay: 118,
    stock: 1,
    featured: true,
    shortDescription: "Switcher 8 canales todo-en-uno con streaming RTMP.",
    description:
      "Estación de realización portátil con hasta 8 entradas (HDMI + SDI), monitor táctil, streaming directo a RTMP/NDI, grabación interna y transición PGM/PVW. La solución más completa para streaming de conciertos sin rack.",
    specs: [
      { label: "Entradas", value: "4x HDMI + 4x SDI" },
      { label: "Salidas", value: "HDMI + SDI + USB" },
      { label: "Streaming", value: "RTMP · NDI · YouTube · Twitch" },
      { label: "Resolución", value: "Hasta 4K 60p" },
      { label: "Pantalla", value: 'Táctil 10.1"' },
    ],
    includes: ["Fuente de alimentación", "Funda de transporte"],
    image: "/products/yolobox-extreme.jpg",
    gallery: ["/products/yolobox-extreme.jpg", "/video-switcher-mixer-broadcast-buttons.jpg"],
  },
  {
    slug: "roland-v1-hd",
    name: "Roland V-1HD",
    brand: "Roland",
    category: "mixers",
    categoryLabel: "Mixers de vídeo",
    pricePerDay: 28,
    stock: 1,
    featured: true,
    shortDescription: "Switcher HDMI 4 canales compacto y fiable.",
    description:
      "Mezclador HDMI de 4 canales con T-bar, efectos y conmutación limpia. La opción compacta para directos pequeños y streaming musical cuando no se necesita SDI.",
    specs: [
      { label: "Entradas", value: "4x HDMI" },
      { label: "Salidas", value: "2x HDMI + USB" },
      { label: "Resolución", value: "1080p" },
      { label: "Transiciones", value: "Cut / Mix / Wipe" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/products/roland-v1hd-dark.jpg",
    gallery: ["/products/roland-v1hd-dark.jpg", "/roland-video-mixer-professional.jpg"],
  },
  {
    slug: "conmutador-hdmi-4x1-multiviewer",
    name: "Conmutador HDMI 4×1 Multi-Viewer",
    brand: "Generic",
    category: "mixers",
    categoryLabel: "Mixers de vídeo",
    pricePerDay: 1,
    stock: 1,
    shortDescription: "Quad Multi-Viewer 4K con salida USB para streaming.",
    description:
      "Conmutador HDMI 4×1 con Multi-Viewer (quad, PiP, fullscreen) y salida USB 3.0 de captura. Útil para previsualizar cuatro fuentes o alimentar un PC de streaming directamente.",
    specs: [
      { label: "Entradas", value: "4x HDMI" },
      { label: "Salidas", value: "HDMI + USB 3.0 capture" },
      { label: "Modos", value: "Quad · PiP · Fullscreen" },
      { label: "Resolución", value: "4K HDMI in · 1080p USB out" },
    ],
    includes: ["Fuente de alimentación", "Cable USB"],
    image: "/products/conmutador-hdmi-4x1.jpg",
    gallery: ["/products/conmutador-hdmi-4x1.jpg"],
  },

  // ───────── MONITORES ─────────
  {
    slug: "monitor-de-campo",
    name: 'Monitor de campo 7"',
    brand: "Generic",
    category: "monitores",
    categoryLabel: "Monitores",
    pricePerDay: 13,
    stock: 1,
    shortDescription: 'Monitor on-camera 7" HDMI para operador.',
    description:
      'Monitor de campo HDMI de 7" con peaking, falso color y zebra. Para operador, foquista o referencia de realización.',
    specs: [
      { label: "Tamaño", value: "7 pulgadas" },
      { label: "Entradas", value: "HDMI" },
      { label: "Brillo", value: "400 nits" },
    ],
    includes: ["Batería NP-F", "Cargador", "Cable HDMI 50 cm"],
    image: "/products/monitor-campo-neewer.jpg",
    gallery: ["/products/monitor-campo-neewer.jpg"],
  },
  {
    slug: "monitor-neofyte",
    name: "Monitor Neofyte",
    brand: "Neofyte",
    category: "monitores",
    categoryLabel: "Monitores",
    pricePerDay: 15,
    stock: 1,
    shortDescription: "Monitor de referencia para realización.",
    description: "Monitor compacto pensado como referencia PGM/PVW en puesto de realización.",
    specs: [
      { label: "Entradas", value: "HDMI" },
      { label: "Alimentación", value: "DC 12V" },
    ],
    includes: ["Fuente de alimentación", "Soporte"],
    image: "/products/pantalla-monitor-neofyte.jpg",
    gallery: ["/products/pantalla-monitor-neofyte.jpg"],
  },

  // ───────── AUDIO ─────────
  {
    slug: "zoom-livetrak-l8",
    name: "Zoom LiveTrak L-8",
    brand: "Zoom",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 42,
    stock: 1,
    shortDescription: "Mixer/grabadora 8 canales con pads y faders.",
    description:
      "Mesa de mezclas y grabadora multipista de 8 canales con 6 pads asignables y monitorado independiente. Ideal para podcast, directo y realización musical pequeña.",
    specs: [
      { label: "Canales", value: "8 (6 XLR/TRS + 2 stereo)" },
      { label: "Grabación", value: "12 pistas simultáneas" },
      { label: "Interfaz", value: "USB audio 12-in / 4-out" },
    ],
    includes: ["Fuente de alimentación", "Cable USB"],
    image: "/products/zoom-l8-dark.jpg",
    gallery: ["/products/zoom-l8-dark.jpg"],
  },
  {
    slug: "focusrite-scarlett-2i4",
    name: "Focusrite Scarlett 2i4",
    brand: "Focusrite",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 22,
    stock: 1,
    shortDescription: "Interfaz de audio USB 2 in / 4 out.",
    description:
      "Interfaz de audio USB con dos preamplificadores Focusrite, ideal para captura de audio broadcast en streaming.",
    specs: [
      { label: "Entradas", value: "2x XLR/TRS combo" },
      { label: "Salidas", value: "4 (2 monitor + 2 line)" },
      { label: "Conversión", value: "24 bit / 192 kHz" },
    ],
    includes: ["Cable USB"],
    image: "/products/focusrite-scarlett-dark.jpg",
    gallery: ["/products/focusrite-scarlett-dark.jpg"],
  },
  {
    slug: "tascam-dr40",
    name: "Tascam DR-40",
    brand: "Tascam",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 15,
    stock: 1,
    shortDescription: "Grabadora de campo 4 pistas con XLR.",
    description: "Grabadora de mano de 4 pistas con micros estéreo y entradas XLR/TRS. Respaldo de audio o backup.",
    specs: [
      { label: "Pistas", value: "4" },
      { label: "Entradas", value: "2x XLR/TRS + micros internos" },
      { label: "Soporte", value: "SD / SDHC / SDXC" },
    ],
    includes: ["Pilas AA", "Funda"],
    image: "/products/tascam-dr40-dark.jpg",
    gallery: ["/products/tascam-dr40-dark.jpg"],
  },
  {
    slug: "hollyland-intercom-solidcom",
    name: "Hollyland Solidcom Intercom",
    brand: "Hollyland",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 48,
    stock: 1,
    featured: true,
    shortDescription: "Sistema intercom wireless, 3 headsets.",
    description:
      "Sistema de intercom inalámbrico full-duplex con 3 estaciones/headsets. Comunicación entre realización, cámaras y FOH sin cableado.",
    specs: [
      { label: "Unidades", value: "3 headsets + hub" },
      { label: "Alcance", value: "Hasta 350 m línea de vista" },
      { label: "Autonomía", value: "10 h" },
    ],
    includes: ["3x headsets", "Base/hub", "Cables de carga"],
    image: "/products/intercomunicadores.jpg",
    gallery: ["/products/intercomunicadores.jpg"],
  },
  {
    slug: "hollyland-lark-wireless-mics",
    name: "Hollyland Lark · micros inalámbricos",
    brand: "Hollyland",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 16,
    stock: 1,
    shortDescription: "Kit de microfonía inalámbrica de solapa.",
    description: "Sistema dual de micrófonos inalámbricos de solapa con caja de carga y receptor de cámara.",
    specs: [
      { label: "Canales", value: "2" },
      { label: "Alcance", value: "200 m" },
      { label: "Autonomía", value: "8 h" },
    ],
    includes: ["2x TX", "1x RX", "Caja de carga", "Cables TRS/TRRS/Lightning"],
    image: "/products/hollyland-lark-dark.jpg",
    gallery: ["/products/hollyland-lark-dark.jpg"],
  },
  {
    slug: "transmisor-audio-rca",
    name: "Transmisor de audio inalámbrico RCA",
    brand: "Generic",
    category: "audio",
    categoryLabel: "Audio",
    pricePerDay: 8,
    stock: 1,
    shortDescription: "Pareja TX/RX de audio estéreo con RCA.",
    description:
      "Sistema inalámbrico de audio con entradas/salidas RCA. Para envío de audio desde mesa FOH a realización o streaming sin tirar cableado largo.",
    specs: [
      { label: "Entradas/Salidas", value: "2x RCA estéreo" },
      { label: "Alcance", value: "50 m línea de vista" },
      { label: "Latencia", value: "< 20 ms" },
    ],
    includes: ["TX + RX", "Antenas", "Alimentación"],
    image: "/products/transmisor-audio-rca.jpg",
    gallery: ["/products/transmisor-audio-rca.jpg"],
  },

  // ───────── CAPTURADORAS ─────────
  {
    slug: "atomos-ninja-4k",
    name: "Atomos Ninja 4K",
    brand: "Atomos",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 30,
    stock: 1,
    featured: true,
    shortDescription: "Grabador/monitor 4K ProRes con HDMI.",
    description:
      "Grabador y monitor 4K con grabación ProRes/DNx vía HDMI. Monitor brillante para operador y respaldo de señal sin compresión.",
    specs: [
      { label: "Entradas", value: "HDMI 2.0" },
      { label: "Códecs", value: "ProRes · DNxHR" },
      { label: "Pantalla", value: '5" 1000 nits' },
    ],
    includes: ["2x batería NP-F", "Cargador", "SSD 500 GB"],
    image: "/products/atomos-ninja-v.jpg",
    gallery: ["/products/atomos-ninja-v.jpg"],
  },
  {
    slug: "atomos-ninja-2",
    name: "Atomos Ninja 2",
    brand: "Atomos",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 25,
    stock: 1,
    shortDescription: "Grabador externo Full HD ProRes.",
    description: "Grabador externo Full HD ProRes por HDMI. Opción económica para grabación de backup.",
    specs: [
      { label: "Entradas", value: "HDMI" },
      { label: "Códecs", value: "ProRes" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["Batería", "Cargador", "HDD"],
    image: "/products/atomos-ninja-2.jpg",
    gallery: ["/products/atomos-ninja-2.jpg"],
  },
  {
    slug: "avio-4k-capture",
    name: "AVIO 4K Capture Card",
    brand: "Epiphan",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 30,
    stock: 1,
    shortDescription: "Tarjeta de captura 4K HDMI → USB 3.0.",
    description:
      "Capturadora externa Epiphan AV.io 4K con loop-out HDMI. Pensada para alimentar un PC de streaming desde cualquier cámara con salida HDMI.",
    specs: [
      { label: "Entrada", value: "HDMI 2.0" },
      { label: "Salida", value: "USB 3.0" },
      { label: "Resolución", value: "4K 30p · 1080p 60p" },
    ],
    includes: ["Cable USB"],
    image: "/products/avio-4k-dark.jpg",
    gallery: ["/products/avio-4k-dark.jpg"],
  },
  {
    slug: "capturadora-usb-hd",
    name: "Capturadora USB HDMI",
    brand: "Generic",
    category: "capturadoras",
    categoryLabel: "Capturadoras",
    pricePerDay: 1,
    stock: 3,
    shortDescription: "Capturadora USB HDMI 1080p.",
    description:
      "Capturadora USB HDMI genérica, 1080p. Útil para streaming básico o como backup en realización.",
    specs: [
      { label: "Entrada", value: "HDMI" },
      { label: "Salida", value: "USB 2.0" },
      { label: "Resolución", value: "1080p 30" },
    ],
    includes: ["Capturadora", "Cable HDMI corto"],
    image: "/products/capturadora-hdmi-generica.jpg",
    gallery: ["/products/capturadora-hdmi-generica.jpg"],
  },

  // ───────── TRANSMISORES INALÁMBRICOS ─────────
  {
    slug: "hollyland-4k-wireless",
    name: "Hollyland 4K Wireless",
    brand: "Hollyland",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 30,
    stock: 1,
    featured: true,
    shortDescription: "Transmisor inalámbrico 4K hasta 150 m.",
    description:
      "Transmisor wireless 4K con HDMI para realización sin cables. Baja latencia y alcance útil en recintos grandes.",
    specs: [
      { label: "Entrada/Salida", value: "HDMI 2.0" },
      { label: "Alcance", value: "150 m" },
      { label: "Latencia", value: "< 60 ms" },
      { label: "Resolución", value: "4K 30p / 1080p 60p" },
    ],
    includes: ["TX + RX", "Antenas", "Cables HDMI cortos", "Baterías NP-F"],
    image: "/products/transmisor-hollyland-pyro.jpg",
    gallery: ["/products/transmisor-hollyland-pyro.jpg"],
  },
  {
    slug: "shimbol-tp-mini",
    name: "Shimbol TP Mini Sistema",
    brand: "Shimbol",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 23,
    stock: 3,
    shortDescription: "Transmisor wireless HDMI compacto, 100 m.",
    description:
      "Sistema inalámbrico HDMI compacto Shimbol TP Mini. Pareja TX/RX para envío a realización, monitor de director o streaming.",
    specs: [
      { label: "Entrada/Salida", value: "HDMI" },
      { label: "Alcance", value: "100 m línea de vista" },
      { label: "Resolución", value: "1080p 60" },
    ],
    includes: ["TX + RX", "Cables HDMI", "Baterías"],
    image: "/products/transmisor-shimbol.jpg",
    gallery: ["/products/transmisor-shimbol.jpg"],
  },
  {
    slug: "transmisor-generico-hdmi",
    name: "Transmisor HDMI genérico",
    brand: "Generic",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 7,
    stock: 1,
    shortDescription: "Transmisor HDMI inalámbrico de apoyo.",
    description: "Pareja TX/RX HDMI para distancias cortas. Útil como backup o redundancia.",
    specs: [
      { label: "Entrada/Salida", value: "HDMI" },
      { label: "Alcance", value: "50 m" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["TX + RX", "Cables"],
    image: "/products/transmisor-generico.jpg",
    gallery: ["/products/transmisor-generico.jpg"],
  },
  {
    slug: "camwave-transmitter",
    name: "Camwave Transmisor",
    brand: "Camwave",
    category: "transmisores",
    categoryLabel: "Transmisores inalámbricos",
    pricePerDay: 5,
    stock: 1,
    shortDescription: "Transmisor wireless Full HD low-cost.",
    description: "Transmisor inalámbrico compacto para distancias cortas, ideal como pool de cámara a monitor.",
    specs: [
      { label: "Entrada", value: "HDMI" },
      { label: "Alcance", value: "30 m" },
      { label: "Resolución", value: "1080p" },
    ],
    includes: ["TX + RX"],
    image: "/products/transmisor-camwave.jpg",
    gallery: ["/products/transmisor-camwave.jpg"],
  },

  // ──��─��������─── CONVERSORES ─────────
  {
    slug: "conversor-hdmi-a-sdi",
    name: "Blackmagic Micro Converter HDMI → SDI",
    brand: "Blackmagic Design",
    category: "conversores",
    categoryLabel: "Conversores",
    pricePerDay: 11,
    stock: 2,
    shortDescription: "Convierte HDMI a 3G-SDI con doble salida.",
    description:
      "Micro Converter Blackmagic HDMI a SDI con doble salida 3G-SDI. Imprescindible para integrar cámaras HDMI en flujos SDI de realización broadcast.",
    specs: [
      { label: "Entrada", value: "HDMI" },
      { label: "Salida", value: "2x 3G-SDI" },
      { label: "Resolución", value: "Hasta 1080p 60" },
      { label: "Alimentación", value: "USB-C" },
    ],
    includes: ["Alimentación USB"],
    image: "/products/bmd-hdmi-to-sdi.jpg",
    gallery: ["/products/bmd-hdmi-to-sdi.jpg"],
  },
  {
    slug: "conversor-sdi-a-hdmi",
    name: "Blackmagic Micro Converter SDI → HDMI",
    brand: "Blackmagic Design",
    category: "conversores",
    categoryLabel: "Conversores",
    pricePerDay: 11,
    stock: 1,
    shortDescription: "Convierte 3G-SDI a HDMI con loop out.",
    description:
      "Micro Converter Blackmagic SDI a HDMI 3G, con loop out. Necesario para sacar señal SDI a monitores de consumo, capturadoras o proyectores.",
    specs: [
      { label: "Entrada", value: "3G-SDI" },
      { label: "Salida", value: "HDMI + SDI loop" },
      { label: "Resolución", value: "Hasta 1080p 60" },
      { label: "Alimentación", value: "USB-C" },
    ],
    includes: ["Alimentación USB"],
    image: "/products/bmd-sdi-to-hdmi.jpg",
    gallery: ["/products/bmd-sdi-to-hdmi.jpg"],
  },

  // ───────── SPLITTERS ─────────
  {
    slug: "splitter-video-hdmi",
    name: "Splitter HDMI 1×4",
    brand: "eSYNiC",
    category: "splitters",
    categoryLabel: "Splitters",
    pricePerDay: 2,
    stock: 2,
    shortDescription: "Distribuidor HDMI 1×4 con indicadores LED.",
    description:
      "Splitter HDMI 1×4 eSYNiC para distribuir una misma señal a cuatro destinos (monitorado, streaming, proyección, captura). LEDs independientes por salida para diagnóstico rápido en directo.",
    specs: [
      { label: "Entradas", value: "1x HDMI" },
      { label: "Salidas", value: "4x HDMI" },
      { label: "Resolución", value: "1080p 60" },
      { label: "Indicadores", value: "LED por salida" },
    ],
    includes: ["Fuente de alimentación"],
    image: "/products/splitter-hdmi-1x4.jpg",
    gallery: ["/products/splitter-hdmi-1x4.jpg"],
  },
  {
    slug: "splitter-hdmi-1x2-4k",
    name: "Splitter HDMI 1×2 4K",
    brand: "Generic",
    category: "splitters",
    categoryLabel: "Splitters",
    pricePerDay: 2,
    stock: 2,
    shortDescription: "Distribuidor HDMI 1×2 compatible 4K y 3D.",
    description:
      "Splitter HDMI compacto 1×2 con soporte 4K UHD y 3D. Ideal para doblar la señal hacia monitor de escena y realización sin latencia apreciable.",
    specs: [
      { label: "Entradas", value: "1x HDMI" },
      { label: "Salidas", value: "2x HDMI" },
      { label: "Resolución", value: "4K UHD / 3D" },
      { label: "Alimentación", value: "DC 5V" },
    ],
    includes: ["Fuente de alimentación DC 5V"],
    image: "/products/splitter-hdmi-1x2.jpg",
    gallery: ["/products/splitter-hdmi-1x2.jpg"],
  },
  {
    slug: "splitter-audio",
    name: "Splitter AV RCA 1×4",
    brand: "Generic",
    category: "splitters",
    categoryLabel: "Splitters",
    pricePerDay: 2,
    stock: 1,
    shortDescription: "Distribuidor audio/vídeo RCA de 4 salidas.",
    description:
      "Splitter AV RCA de 1 entrada a 4 salidas con vídeo compuesto (amarillo) y audio estéreo L/R (blanco/rojo). Útil para monitorado paralelo desde mesa a varios destinos o fuentes legacy que aún viajan por RCA.",
    specs: [
      { label: "Entradas", value: "1 AV (CVBS + L/R)" },
      { label: "Salidas", value: "4 AV (CVBS + L/R)" },
      { label: "Alimentación", value: "DC 9V" },
    ],
    includes: ["Fuente de alimentación DC 9V"],
    image: "/products/splitter-audio-1x4.jpg",
    gallery: ["/products/splitter-audio-1x4.jpg"],
  },

  // ───────── CABLEADO ─────────
  {
    slug: "cable-hdmi-fibra-30m",
    name: "Cable HDMI fibra óptica 30 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 14,
    stock: 8,
    shortDescription: "HDMI 2.0 fibra óptica 4K, 30 metros.",
    description:
      "Cable HDMI de fibra óptica activa de 30 m. Imprescindible para tiradas largas entre escenario y realización sin pérdida de señal 4K.",
    specs: [
      { label: "Longitud", value: "30 m" },
      { label: "Tipo", value: "Fibra óptica activa" },
      { label: "Resolución", value: "4K 60p" },
    ],
    includes: ["Cable"],
    image: "/products/cable-hdmi-30mt.jpg",
    gallery: ["/products/cable-hdmi-30mt.jpg"],
  },
  {
    slug: "cable-sdi-30m",
    name: "Cable SDI 30 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 22,
    stock: 1,
    shortDescription: "Cable 3G-SDI con conectores BNC, 30 m.",
    description:
      "Cable 3G-SDI de 30 m con BNC. Estándar para distribución de vídeo en realización broadcast y en directo.",
    specs: [
      { label: "Longitud", value: "30 m" },
      { label: "Conectores", value: "BNC · BNC" },
      { label: "Ancho de banda", value: "3G-SDI" },
    ],
    includes: ["Cable"],
    image: "/products/cable-sdi-30m-dark.jpg",
    gallery: ["/products/cable-sdi-30m-dark.jpg"],
  },
  {
    slug: "cable-hdmi-10m",
    name: "Cable HDMI 10 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 2,
    shortDescription: "HDMI 2.0 de cobre, 10 m, conectores dorados.",
    description:
      "Latiguillo HDMI de cobre de 10 metros con conectores bañados en oro y carcasa reforzada. Apto para 1080p y 4K a corta distancia.",
    specs: [
      { label: "Longitud", value: "10 m" },
      { label: "Tipo", value: "Cobre" },
      { label: "Conectores", value: "HDMI 2.0 dorados" },
    ],
    includes: ["Cable"],
    image: "/products/cable-hdmi-10m.jpg",
    gallery: ["/products/cable-hdmi-10m.jpg"],
  },
  {
    slug: "cable-hdmi-5m",
    name: "Cable HDMI 5 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 4,
    shortDescription: "HDMI 2.0 de cobre, 5 m, conectores dorados.",
    description:
      "Latiguillo HDMI de cobre de 5 metros con conectores bañados en oro. Distancia cómoda para interconexión en rack entre mixer, capturadora y monitor.",
    specs: [
      { label: "Longitud", value: "5 m" },
      { label: "Tipo", value: "Cobre" },
      { label: "Conectores", value: "HDMI 2.0 dorados" },
    ],
    includes: ["Cable"],
    image: "/products/cable-hdmi-5m.jpg",
    gallery: ["/products/cable-hdmi-5m.jpg"],
  },
  {
    slug: "cable-mini-hdmi-a-hdmi",
    name: "Cable mini HDMI → HDMI",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Cable mini HDMI para cámaras.",
    description: "Cable mini HDMI a HDMI estándar, para salida de cámaras tipo Sony RX100 o DSLR.",
    specs: [
      { label: "Longitud", value: "1 m" },
      { label: "Tipo", value: "Mini HDMI · HDMI" },
    ],
    includes: ["Cable"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "cable-hdmi-corto-50cm",
    name: "Cable HDMI corto 25-50 cm",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Latiguillos cortos para jaula y rig.",
    description: "Cables HDMI cortos de 25 y 50 cm, ideales para monitor on-camera o interconexión en rig.",
    specs: [
      { label: "Longitud", value: "25 – 50 cm" },
      { label: "Color", value: "Amarillo alta visibilidad" },
    ],
    includes: ["Cable"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "adaptador-mini-hdmi",
    name: "Adaptador mini HDMI",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Adaptador mini HDMI a HDMI hembra.",
    description: "Adaptador compacto para convertir salida mini HDMI en HDMI estándar.",
    specs: [{ label: "Tipo", value: "Mini HDMI M · HDMI H" }],
    includes: ["Adaptador"],
    image: "/hdmi-cable-coiled-black-professional.jpg",
    gallery: ["/hdmi-cable-coiled-black-professional.jpg"],
  },
  {
    slug: "cable-rca-5m",
    name: "Cable RCA 5 m",
    brand: "Generic",
    category: "cableado",
    categoryLabel: "Cableado",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Cable RCA estéreo, 5 m.",
    description: "Cable RCA estéreo de 5 m para envíos de audio.",
    specs: [
      { label: "Longitud", value: "5 m" },
      { label: "Conectores", value: "2x RCA · 2x RCA" },
    ],
    includes: ["Cable"],
    image: "/coiled-bnc-sdi-cable-professional.jpg",
    gallery: ["/coiled-bnc-sdi-cable-professional.jpg"],
  },

  // ���──────── TRÍPODES ─────────
  {
    slug: "tripode-base-monopie",
    name: "Base trípode para monopie",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 8,
    stock: 2,
    shortDescription: "Base articulada para estabilizar monopie.",
    description:
      "Base de tres patas articuladas en aluminio con rosca 1/4\" superior. Se acopla a monopie para estabilizar la cámara y permitir ligera movilidad lateral durante la toma en directo.",
    specs: [
      { label: "Material", value: "Aluminio" },
      { label: "Rosca", value: '1/4"' },
      { label: "Plegable", value: "Sí" },
    ],
    includes: ["Base articulada"],
    image: "/products/tripode-fuerte-base-v2.jpg",
    gallery: ["/products/tripode-fuerte-base-v2.jpg"],
  },
  {
    slug: "tripode-cayer",
    name: "Trípode Cayer · heavy duty",
    brand: "Cayer",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 16,
    stock: 1,
    shortDescription: "Trípode de vídeo profesional con cabeza fluida.",
    description:
      "Trípode de vídeo Cayer de grado broadcast con cabeza fluida, barra de pan extraíble y middle spreader para mayor estabilidad. Bloqueos de leva en las secciones para montaje rápido en directo.",
    specs: [
      { label: "Carga máxima", value: "6 kg" },
      { label: "Altura máxima", value: "160 cm" },
      { label: "Cabeza", value: "Fluida con barra de pan" },
      { label: "Estabilizador", value: "Middle spreader" },
    ],
    includes: ["Zapata", "Barra de pan", "Funda"],
    image: "/products/tripode-heavy-duty.jpg",
    gallery: ["/products/tripode-heavy-duty.jpg"],
  },
  {
    slug: "monopie-cayer",
    name: "Monopie Cayer",
    brand: "Cayer",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 16,
    stock: 1,
    shortDescription: "Monopie de vídeo con base estable.",
    description: "Monopie Cayer con base desplegable, cabeza de vídeo fluida y pies estabilizadores. Para operador en directo.",
    specs: [
      { label: "Carga máxima", value: "5 kg" },
      { label: "Altura máxima", value: "180 cm" },
    ],
    includes: ["Base plegable", "Funda"],
    image: "/products/monopie-cayer.jpg",
    gallery: ["/products/monopie-cayer.jpg"],
  },
  {
    slug: "tripode-pequeno-estable",
    name: "Trípode Manbily · pequeño estable",
    brand: "Manbily",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 7,
    stock: 1,
    shortDescription: "Trípode compacto de bajo perfil.",
    description:
      "Trípode compacto y estable Manbily, cabeza plegable. Para cámaras pequeñas o en ubicaciones de bajo perfil.",
    specs: [
      { label: "Altura", value: "20 cm (plegable)" },
      { label: "Marca", value: "Manbily" },
    ],
    includes: ["Trípode plegable"],
    image: "/products/mini-tripode-fuerte.jpg",
    gallery: ["/products/mini-tripode-fuerte.jpg"],
  },
  {
    slug: "tripode-mini",
    name: "Mini trípode Zeadio",
    brand: "Zeadio",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 5,
    shortDescription: "Mini-trípode para cámara compacta y POV.",
    description: "Mini trípode Zeadio de aluminio con cabeza de bola y plato rápido. Para RX100, móviles o cámaras de acción.",
    specs: [
      { label: "Altura máxima", value: "20 cm" },
      { label: "Cabeza", value: "Bola con plato rápido" },
    ],
    includes: ["Trípode"],
    image: "/products/mini-tripode-zeadio.jpg",
    gallery: ["/products/mini-tripode-zeadio.jpg"],
  },
  {
    slug: "tripode-manfrotto-mini",
    name: "Manfrotto PIXI",
    brand: "Manfrotto",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 4,
    shortDescription: "Mini trípode Manfrotto PIXI para POV.",
    description: "Trípode Manfrotto PIXI de mesa, diseño ergonómico y construcción sólida. Tope de carga mayor que alternativas genéricas.",
    specs: [
      { label: "Altura máxima", value: "18,5 cm" },
      { label: "Carga", value: "1 kg" },
    ],
    includes: ["Trípode"],
    image: "/products/mini-tripode-manfrotto-pixi.jpg",
    gallery: ["/products/mini-tripode-manfrotto-pixi.jpg"],
  },
  {
    slug: "tripode-base-larga",
    name: "Mini trípode Zeadio · base larga",
    brand: "Zeadio",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Mini-trípode Zeadio con patas extendidas.",
    description:
      "Mini trípode Zeadio de sobremesa con patas de aluminio extendidas y cabeza de bola compacta con pomo de bloqueo lateral. Base amplia para estabilidad extra sobre superficies irregulares con cámaras ligeras y móviles.",
    specs: [
      { label: "Altura máxima", value: "15 cm" },
      { label: "Cabeza", value: "Bola con pomo lateral" },
      { label: "Rosca", value: '1/4"' },
    ],
    includes: ["Trípode"],
    image: "/products/mini-tripode-zeadio-base-larga.jpg",
    gallery: ["/products/mini-tripode-zeadio-base-larga.jpg"],
  },
  {
    slug: "tripode-fondo-blanco",
    name: "Trípode para fondo",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 1,
    shortDescription: "Soporte telescópico para fondos.",
    description: "Sistema de soporte de fondo para plató (dos pies + barra horizontal).",
    specs: [
      { label: "Altura máxima", value: "300 cm" },
      { label: "Ancho", value: "3 m" },
    ],
    includes: ["2 pies", "Barra telescópica", "Funda"],
    image: "/light-stand-tripod-telescopic.jpg",
    gallery: ["/light-stand-tripod-telescopic.jpg"],
  },
  {
    slug: "tripode-de-luz",
    name: "Trípode de luz",
    brand: "Generic",
    category: "tripodes",
    categoryLabel: "Trípodes",
    pricePerDay: 4,
    stock: 7,
    shortDescription: "Pie de luz telescópico.",
    description: 'Pie de luz estándar para LED on-stand, flashes o accesorios con rosca 1/4" y 3/8".',
    specs: [
      { label: "Altura máxima", value: "220 cm" },
      { label: "Rosca", value: '1/4" y 3/8"' },
    ],
    includes: ["Pie de luz"],
    image: "/light-stand-tripod-telescopic.jpg",
    gallery: ["/light-stand-tripod-telescopic.jpg"],
  },

  // ───────── GRIPS ─────────
  {
    slug: "brazo-manfrotto-grande",
    name: "Brazo Manfrotto grande",
    brand: "Manfrotto",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 12,
    stock: 3,
    shortDescription: "Brazo mágico Manfrotto articulado.",
    description:
      "Brazo articulado Manfrotto grande, muy resistente. Para sujetar monitores, luces o cámaras pequeñas a estructuras. Incluye Super Clamp.",
    specs: [
      { label: "Carga", value: "Hasta 3 kg" },
      { label: "Extensión", value: "55 cm" },
    ],
    includes: ["Brazo Manfrotto", "Super Clamp"],
    image: "/products/brazo-manfrotto-dark.jpg",
    gallery: ["/products/brazo-manfrotto-dark.jpg"],
  },
  {
    slug: "brazo-magico-neewer-std",
    name: "Brazo mágico Neewer · estándar",
    brand: "Neewer",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Brazo articulado para monitor on-camera.",
    description: "Brazo mágico Neewer tamaño estándar para monitor, luz o micro en jaula.",
    specs: [
      { label: "Carga", value: "Hasta 1.5 kg" },
      { label: "Longitud", value: "28 cm" },
    ],
    includes: ["Brazo", "Super Clamp"],
    image: "/products/brazo-magico-standard-dark.jpg",
    gallery: ["/products/brazo-magico-standard-dark.jpg"],
  },
  {
    slug: "brazo-magico-neewer-med",
    name: "Brazo mágico Neewer · mediano",
    brand: "Neewer",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 2,
    stock: 6,
    shortDescription: "Brazo articulado mediano.",
    description: "Brazo mágico Neewer mediano con super clamp, para accesorios ligeros en jaula o estructura.",
    specs: [{ label: "Longitud", value: "20 cm" }],
    includes: ["Brazo", "Super Clamp"],
    image: "/products/brazo-magico-mediano-dark.jpg",
    gallery: ["/products/brazo-magico-mediano-dark.jpg"],
  },
  {
    slug: "brazo-magico-neewer-peq",
    name: "Brazo mágico Neewer · pequeño",
    brand: "Neewer",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Brazo articulado compacto con super clamp.",
    description:
      "Brazo mágico pequeño con super clamp y cabeza de bola única con mango de caucho estriado. Pomo rojo de bloqueo rápido. Ideal para micros de cañón, luces de bolsillo o accesorios ligeros en jaula.",
    specs: [
      { label: "Longitud", value: "12 cm" },
      { label: "Bloqueo", value: "Mango estriado + pomo" },
      { label: "Rosca", value: '1/4"' },
    ],
    includes: ["Brazo", "Super Clamp"],
    image: "/products/brazo-magico-pequeno.jpg",
    gallery: ["/products/brazo-magico-pequeno.jpg"],
  },
  {
    slug: "smallrig-super-clamp",
    name: "SmallRig Super Clamp + ballhead",
    brand: "SmallRig",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 2,
    stock: 2,
    shortDescription: "Super Clamp con cabeza doble de bola.",
    description:
      "Super Clamp SmallRig con cabeza articulada de doble bola y rosca 1/4\" superior. Para fijar monitores, luces o micros a tubos de 15-55 mm y estructura de escenario con posicionamiento preciso.",
    specs: [
      { label: "Apertura", value: "15 – 55 mm" },
      { label: "Rosca", value: '1/4" y 3/8"' },
      { label: "Cabeza", value: "Doble ballhead" },
    ],
    includes: ["Super Clamp", "Ballhead"],
    image: "/products/brazo-magico-smallrig.jpg",
    gallery: ["/products/brazo-magico-smallrig.jpg"],
  },
  {
    slug: "slider-motorizado",
    name: "Slider motorizado Edelkrone",
    brand: "Edelkrone",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 1,
    shortDescription: "Slider motorizado compacto.",
    description: "Slider motorizado Edelkrone para movimientos de cámara cortos con control de velocidad.",
    specs: [
      { label: "Recorrido", value: "40 cm" },
      { label: "Motorización", value: "Velocidad variable" },
    ],
    includes: ["Slider", "Mando", "Batería"],
    image: "/products/slider-edelkrone.jpg",
    gallery: ["/products/slider-edelkrone.jpg"],
  },
  {
    slug: "palo-selfie",
    name: "Palo selfie Insta360",
    brand: "Insta360",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 4,
    shortDescription: "Invisible stick para cámara 360.",
    description:
      "Palo selfie Insta360 (invisible stick) con grip de goma trenzada y rosca 1/4\" superior. Diseñado para desaparecer en el reframe 360 y obtener planos aéreos desde la mano durante el directo.",
    specs: [
      { label: "Compatibilidad", value: "Cámaras 360 y acción" },
      { label: "Grip", value: "Goma trenzada" },
      { label: "Rosca", value: '1/4"' },
    ],
    includes: ["Palo"],
    image: "/products/palo-selfie-insta360.jpg",
    gallery: ["/products/palo-selfie-insta360.jpg"],
  },
  {
    slug: "tripode-movil-extensible",
    name: "Trípode móvil extensible",
    brand: "Generic",
    category: "grips",
    categoryLabel: "Grips",
    pricePerDay: 1,
    stock: 4,
    shortDescription: "Trípode-palo extensible para móvil y cámaras compactas.",
    description:
      "Trípode extensible con patas plegables y cabeza de bola, pensado para móvil, RX100 y cámaras de acción. Perfecto para planos POV, backstage y contenido vertical durante el directo.",
    specs: [
      { label: "Longitud", value: "25 – 90 cm" },
      { label: "Cabeza", value: "Bola con rosca 1/4\"" },
      { label: "Bloqueo", value: "Anillo de giro" },
    ],
    includes: ["Trípode extensible"],
    image: "/products/tripode-movil-extensible.jpg",
    gallery: ["/products/tripode-movil-extensible.jpg"],
  },

  // ───────── LUCES ─────────
  {
    slug: "luz-tubo-godox",
    name: "Luz tubo Godox",
    brand: "Godox",
    category: "luces",
    categoryLabel: "Luces",
    pricePerDay: 4,
    stock: 2,
    featured: true,
    shortDescription: "Tubo LED Godox para efectos practical.",
    description:
      "Tubo LED Godox de luz ajustable para efectos 'practical' en escena: rim lights, rellenos creativos y fondos.",
    specs: [
      { label: "Longitud", value: "60 cm aprox." },
      { label: "Control", value: "Inalámbrico / app" },
      { label: "Autonomía", value: "2 – 4 h" },
    ],
    includes: ["Tubo LED", "Batería interna", "Cargador"],
    image: "/products/luz-tubo-godox.jpg",
    gallery: ["/products/luz-tubo-godox.jpg"],
  },
  {
    slug: "luz-tubo-generica",
    name: "Luz tubo LED genérica",
    brand: "Generic",
    category: "luces",
    categoryLabel: "Luces",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Tubo LED portátil para acento.",
    description: "Tubos LED genéricos para acentos, rellenos pequeños o decoración en plano.",
    specs: [
      { label: "Alimentación", value: "Batería interna" },
      { label: "Control", value: "Botón físico" },
    ],
    includes: ["Tubo LED", "Cable USB"],
    image: "/products/luz-tubo-generica-dark.jpg",
    gallery: ["/products/luz-tubo-generica-dark.jpg"],
  },
  {
    slug: "panel-neewer",
    name: "Panel de luz Neewer",
    brand: "Neewer",
    category: "luces",
    categoryLabel: "Luces",
    pricePerDay: 3,
    stock: 1,
    shortDescription: "Panel LED bicolor con difusor integrado.",
    description:
      "Panel LED Neewer bicolor con difusor integrado y yoke en U para orientación precisa. Luz suave ideal para relleno de cara, zona de entrevista o como key light on-camera.",
    specs: [
      { label: "Tipo", value: "Panel LED bicolor" },
      { label: "Temperatura", value: "3200 – 5600 K" },
      { label: "Alimentación", value: "NP-F / DC" },
      { label: "Montaje", value: "Yoke en U con 3 pomos" },
    ],
    includes: ["Panel", "Difusor", "Yoke", "Batería NP-F"],
    image: "/products/panel-luz-neewer.jpg",
    gallery: ["/products/panel-luz-neewer.jpg"],
  },
  {
    slug: "luz-rgb-portatil",
    name: "Luz RGB portátil VIJIM VL120",
    brand: "VIJIM",
    category: "luces",
    categoryLabel: "Luces",
    pricePerDay: 1,
    stock: 5,
    featured: true,
    shortDescription: "Mini panel RGB recargable para efectos.",
    description:
      "Mini panel RGB de bolsillo con batería interna, ajuste de HUE y efectos (police, fire, lightning). Ideal para acentos de color en plano o iluminación de producto.",
    specs: [
      { label: "Modelo", value: "VIJIM VL120" },
      { label: "RGB", value: "0 – 360° HSI" },
      { label: "Batería", value: "2100 mAh" },
      { label: "Autonomía", value: "Hasta 2 h" },
    ],
    includes: ["Panel RGB", "Cable USB-C"],
    image: "/products/luces-rgb-portatiles.jpg",
    gallery: ["/products/luces-rgb-portatiles.jpg"],
  },

  // ───────── BATERÍAS ─────────
  {
    slug: "neewer-np-f750-pack",
    name: "Pack Neewer NP-F750 + cargador dual",
    brand: "Neewer",
    category: "baterias",
    categoryLabel: "Baterías",
    pricePerDay: 2,
    stock: 4,
    shortDescription: "Pack 2x NP-F750 con cargador dual OLED.",
    description:
      "Pack de 2 baterías Neewer NP-F750 (5200 mAh) con cargador dual USB y display OLED. Compatibles con monitores, luces LED y grabadores de campo.",
    specs: [
      { label: "Modelo", value: "NP-F750" },
      { label: "Capacidad", value: "5200 mAh" },
      { label: "Cargador", value: "Dual USB · OLED" },
    ],
    includes: ["2x NP-F750", "Cargador dual", "Cable USB"],
    image: "/products/neewer-np-f750-pack.jpg",
    gallery: ["/products/neewer-np-f750-pack.jpg"],
  },
  {
    slug: "vrurc-powerbank-20000",
    name: "VRURC Power Bank 20.000 mAh",
    brand: "VRURC",
    category: "baterias",
    categoryLabel: "Baterías",
    pricePerDay: 1,
    stock: 6,
    shortDescription: "Power bank 20.000 mAh con carga rápida 22,5 W.",
    description:
      "Power bank compacto de 20.000 mAh con salida PD/QC 22,5 W. Útil para alimentar monitores, móviles, transmisores o cámaras vía USB-PD.",
    specs: [
      { label: "Capacidad", value: "20.000 mAh" },
      { label: "Salida", value: "USB-A + USB-C PD 22,5 W" },
      { label: "Peso", value: "360 g" },
    ],
    includes: ["Power bank", "Cable USB-C"],
    image: "/products/powerbank.jpg",
    gallery: ["/products/powerbank.jpg"],
  },
  {
    slug: "ssd-atomos-500gb",
    name: "Disco SSD AtomX 500 GB",
    brand: "Angelbird / Atomos",
    category: "baterias",
    categoryLabel: "Baterías",
    pricePerDay: 2,
    stock: 3,
    shortDescription: "SSD AtomX 500 GB para grabadores Atomos.",
    description:
      "Disco SSD AtomX de 500 GB certificado por Atomos y Angelbird, compatible con caddy Atomos para grabación ProRes y DNxHR sin caídas de frame. Ideal para jornadas de directo y realización multicam.",
    specs: [
      { label: "Capacidad", value: "500 GB" },
      { label: "Interfaz", value: "SATA III" },
      { label: "Certificación", value: "Atomos Approved" },
    ],
    includes: ["SSD", "Caddy Atomos"],
    image: "/products/disco-ssd-500gb.jpg",
    gallery: ["/products/disco-ssd-500gb.jpg"],
  },
  {
    slug: "ssd-atomos-1tb",
    name: "Disco SSD Atomos Master Caddy 1 TB",
    brand: "Atomos",
    category: "baterias",
    categoryLabel: "Baterías",
    pricePerDay: 5,
    stock: 1,
    shortDescription: "SSD Atomos Master Caddy 1 TB para grabación prolongada.",
    description:
      "Disco SSD Atomos Master Caddy de 1 TB para grabación prolongada ProRes y DNxHR en Atomos Ninja. Carcasa robusta con ventana de inspección y doble capacidad para rodajes largos sin cambios de soporte.",
    specs: [
      { label: "Capacidad", value: "1 TB" },
      { label: "Interfaz", value: "SATA III" },
      { label: "Certificación", value: "Atomos Approved" },
    ],
    includes: ["SSD", "Caddy Atomos"],
    image: "/products/disco-ssd-1tb.jpg",
    gallery: ["/products/disco-ssd-1tb.jpg"],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured)
}

export function getCategory(slug: ProductCategory) {
  return categories.find((c) => c.slug === slug)
}

export function getProductsByCategory(category: ProductCategory): Product[] {
  return products.filter((p) => p.category === category)
}
